# Generated by Django 6.1 on 2026-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoestoque',
            name='dimensao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produtoestoque',
            name='etiqueta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produtoestoque',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produtoestoque',
            name='peso_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtoestoque',
            name='unidade',
            field=models.CharField(default='UN', max_length=10),
        ),
    ]
