# Generated by Django 6.1 on 2026-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfacao', '0002_avaliacaonps_cliente_gostou'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaonps',
            name='assinatura_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do recebedor'),
        ),
    ]
