# Generated by Django 6.1 on 2026-08-28 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfacao', '0003_avaliacaonps_assinatura_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaonps',
            name='nota_satisfacao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de satisfação'),
        ),
    ]
