# Generated by Django 6.1 on 2026-08-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0004_veiculo_equipe'),
        ('pedidos', '0002_itempedido_codigo_itempedido_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código da Rota')),
                ('data_rota', models.DateField(verbose_name='Data da Rota')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.equipe', verbose_name='Equipe Responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_rota', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(verbose_name='Ordem da Parada')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENTREGUE', 'Entregue'), ('FALHOU', 'Não Entregue')], default='PENDENTE', max_length=20, verbose_name='Status da Parada')),
                ('horario_realizacao', models.DateTimeField(blank=True, null=True, verbose_name='Horário da Entrega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido', verbose_name='Pedido')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='roteirizacao.rota', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Parada da Rota',
                'verbose_name_plural': 'Paradas da Rota',
                'ordering': ['rota', 'sequencia'],
            },
        ),
    ]
