# Generated by Django 6.1 on 2026-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteirizacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradarota',
            name='horario_realizacao',
        ),
        migrations.AddField(
            model_name='paradarota',
            name='chegada_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegada Cliente'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='documento_recebedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento (DOC)'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='finalizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='foto_chegada',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/chegada/', verbose_name='Foto Chegada'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='foto_nota_assinada',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/notas/', verbose_name='Foto Nota Assinada'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='foto_produtos',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/produtos/', verbose_name='Foto Produtos'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='inicio_descarregamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='observacoes_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Observações (Obs)'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='recebedor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Recebedor'),
        ),
        migrations.AddField(
            model_name='paradarota',
            name='saida_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída Entrega'),
        ),
        migrations.AlterField(
            model_name='paradarota',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SAIDA', 'Saída para Entrega'), ('CHEGADA', 'Chegada no Cliente'), ('INICIO', 'Início de Descarregamento'), ('ENTREGA_REALIZADA', 'Entrega Realizada'), ('RESSALVA', 'Entrega Realizada com Ressalvas')], default='PENDENTE', max_length=30, verbose_name='Status da Parada'),
        ),
    ]
