# Generated by Django 6.1 on 2026-08-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_veiculo_equipe'),
        ('roteirizacao', '0002_remove_paradarota_horario_realizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.equipe', verbose_name='Equipe Responsável'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.veiculo', verbose_name='Veículo'),
        ),
    ]
