# Generated by Django 6.1 on 2026-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedid_historico'),
        ('roteirizacao', '0007_rota_ajudantes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paradarota',
            index=models.Index(fields=['status', 'finalizado'], name='roteirizaca_status_e1ae43_idx'),
        ),
    ]
