# Generated by Django 6.1 on 2026-08-19 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('peso_total', models.FloatField(default=0)),
                ('volume_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('Em Rota', 'Em Rota'), ('Entregue', 'Entregue'), ('Ocorrência', 'Ocorrência')], default='Backlog', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura_base64', models.TextField(blank=True, null=True)),
                ('foto_entrega_base64', models.TextField(blank=True, null=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('peso_unitario', models.FloatField(default=0)),
                ('valor_unitario', models.FloatField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produtoestoque')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
        ),
    ]
