# Generated by Django 6.1 on 2026-08-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itempedido_codigo_itempedido_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Rota', 'Em Rota'), ('Saida', 'Saída'), ('Chegada', 'Chegada'), ('Inicio', 'Início'), ('Entregue', 'Entregue'), ('Ocorrência', 'Ocorrência')], default='Pendente', max_length=50),
        ),
    ]
