# Generated by Django 6.1 on 2026-08-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_peso_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_volume_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status_operacional',
            field=models.CharField(default='Disponível', max_length=30),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_equipamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
