# Generated by Django 6.1 on 2026-08-19 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_veiculo_ano_veiculo_capacidade_peso_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Equipe')),
                ('membros_info', models.TextField(blank=True, default='', verbose_name='Membros/Ajudantes')),
                ('ativo', models.BooleanField(default=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_como_motorista', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Principal')),
            ],
        ),
    ]
