# Generated by Django 6.1 on 2026-08-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='cadastros.equipe'),
        ),
    ]
