# Generated by Django 6.1 on 2026-08-21 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_veiculo_equipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, default='', max_length=100, verbose_name='Setor')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail corporativo')),
                ('vinculo', models.CharField(blank=True, default='CLT', max_length=30, verbose_name='Vínculo')),
                ('cnh', models.CharField(blank=True, default='', max_length=20, verbose_name='CNH')),
                ('categoria_cnh', models.CharField(blank=True, default='', max_length=3, verbose_name='Categoria da CNH')),
                ('status_operacional', models.CharField(default='Ativo', max_length=30, verbose_name='Status operacional')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
