# Generated by Django 5.2.17 on 2026-08-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, default='', max_length=20)),
                ('documento_digits', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('tipo', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='JURIDICA', max_length=10)),
                ('papeis', models.CharField(default='DESTINATARIO', max_length=80)),
                ('endereco', models.CharField(blank=True, default='', max_length=500)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=20)),
                ('origem', models.CharField(choices=[('EMISSAO', 'Emissão'), ('MANUAL', 'Manual')], default='EMISSAO', max_length=20)),
                ('qtd_emissoes', models.PositiveIntegerField(default=0)),
                ('ultima_emissao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa / Pessoa',
                'verbose_name_plural': 'Empresas / Pessoas',
                'ordering': ['nome'],
            },
        ),
    ]
