# Generated by Django 5.2.17 on 2026-08-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_pessoaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='tipo_frota',
            field=models.CharField(choices=[('PROPRIA', 'Frota Própria'), ('TERCEIRO', 'Terceiros')], default='PROPRIA', max_length=20, verbose_name='Tipo de frota'),
        ),
    ]
