# Generated by Django 5.2.17 on 2026-08-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_veiculo_tipo_frota'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='agencia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='alimentacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='autorizacao_seguradora',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco',
            field=models.CharField(blank=True, default='BANCO BRADESCO S/A', max_length=80),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cia_transporte',
            field=models.CharField(blank=True, default='CIA DE TRANSPORTE', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh_codigo_seguranca',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh_data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh_data_primeira',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh_uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='companheira',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='conta_numero',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='convenio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps_data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps_numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps_orgao_expedidor',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps_serie',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_autorizacao_seguradora',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dependentes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='desconto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='exame_toxicologico',
            field=models.CharField(blank=True, default='NÃO APLICAVEL', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='inss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='municipio_nascimento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nextel_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nextel_numero',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis_pasep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pix_chave',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pix_tipo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg_data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg_orgao_expedidor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status_seguradora',
            field=models.CharField(blank=True, default='Nao cadastrado', max_length=40),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_cadastro',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_conta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo_data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo_eleitor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo_secao',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo_zona',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.CharField(blank=True, default='CIA DE TRANSPORTE', max_length=120),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='vale_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='validade_seguradora',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo ocupacional'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='categoria_cnh',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Categoria da CNH'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Habilitação (CNH)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
