# Generated by Django 5.2.17 on 2026-08-23 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_funcionario_ficha_completa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='anexos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='antt',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='base_operacao',
            field=models.CharField(blank=True, default='UNIDADE III', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_tanque_litros',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='categoria_frota',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='certificado_cronotacografo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cidade_emplacada',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='codigo_analise_gerenciadora',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='consumo_km_litro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='eixos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='financiamento',
            field=models.CharField(blank=True, default='Nenhum', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='gerenciadora',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='id_rastreador',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='instituicao_financeira',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='itens_adicionais',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_maximo_rota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='medidas_rodado',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_como_motorista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='percentual_frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='primeira_do_dia_diferente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='rastreador',
            field=models.CharField(blank=True, default='(Sem Rastreador)', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='seguradora',
            field=models.CharField(blank=True, default='SEM SEGURO', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status_seguradora',
            field=models.CharField(blank=True, default='Nao cadastrado', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tabela',
            field=models.CharField(blank=True, default='NAO APLICAVEL', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_carroceria',
            field=models.CharField(blank=True, default='Não Aplicável', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_proprietario',
            field=models.CharField(blank=True, default='Proprio', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_responsavel',
            field=models.CharField(blank=True, default='Proprio', max_length=40),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_rodado',
            field=models.CharField(blank=True, default='Nao aplicavel', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='travas_portas_bau',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='uf_emplacada',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='unidade_proprietaria',
            field=models.CharField(blank=True, default='UNIDADE III', max_length=80),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='validade_antt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='validade_checklist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='validade_licenciamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='validade_seguradora',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_licenciamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_por_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_por_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_por_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='vencimento_ipva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
