# Generated by Django 6.1 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_veiculo_ficha_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(
                blank=True,
                related_name='equipes_como_ajudante',
                to='cadastros.funcionario',
                verbose_name='Membros/Ajudantes',
            ),
        ),
    ]
