# Generated by Django 6.1 on 2026-08-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_cargo_usuario_categoria_cnh_usuario_cnh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('TI', 'TI'), ('Admin', 'Admin'), ('Gestor', 'Gestor'), ('Gestor Operacional', 'Gestor Operacional'), ('Operacional', 'Operacional'), ('Motorista', 'Motorista'), ('Ajudante', 'Ajudante')], default='Operacional', max_length=20),
        ),
    ]
